#Who can use revive items
#Allowed Values: REVIVER, FALLEN, BOTH, NONE
Item_User = "BOTH"
#If debug mode should be activated (just for testing and troubleshooting)
Debug_Mode = true
#If Revive Me is enabled
Revive_Me_Enabled = true

["Self-Revive Settings"]

	["Self-Revive Settings"."General Settings"]
		#List of all your self-revive options EXCEPT revive items (Duplicate options are allowed, can be empty). Self-revive options refresh from this list when the revive penalty ends. OPTIONS: 'CHANCE', 'RANDOM_ITEMS', 'KILL', 'STATUS_EFFECTS', 'EXPERIENCE'
		SELF_REVIVE_OPTIONS = ["RANDOM_ITEMS", "CHANCE", "KILL", "STATUS_EFFECTS", "EXPERIENCE"]
		#If self-revive should be disabled if a player places you in the fallen state
		Disable_Self_Revive_On_PVP = false
		#If the chosen self-revive options are picked randomly.
		Randomize_Self_Revive_Options = true
		#If the mod should only pick self-revive options that you would meet the requirements for (when possible)
		Only_Use_Available_Options = false
		#Increases the cost of self-revival options each time you self-revive. Stacks additively. Resets to 0 on fallen penalty timer expiration.
		#Range: 0.0 ~ 1.0
		Self_Penalty_Percentage = 0.25
		#If the revive item list should refresh continuously (if false it will refresh once when entering fallen state)
		Refresh_Item_List = false

	["Self-Revive Settings"."Revive Type Settings"]

		["Self-Revive Settings"."Revive Type Settings".Chance]
			#How high your chance is to revive. (Affected by penalty)
			#Range: 0.0 ~ 1.0
			Revive_Chance = 0.75
			#If you should die instantly if you fail the chance check. (Will only disable self revive if Can_Give_Up is false)
			Kill_On_Fail = false

		["Self-Revive Settings"."Revive Type Settings"."Random Items"]
			#Percentage to lose for sacrificial items. (Affected by penalty)
			#Range: 0.0 ~ 1.0
			Item_Loss_Percentage = 0.25
			#Should check hotbar when sacrificing items
			Include_Hotbar_Items = false

		["Self-Revive Settings"."Revive Type Settings".Kill]
			#Amount of Living Entities you must kill before the death timer runs out.
			#Range: > 0
			Kill_Count = 2
			#Time in SECONDS you have to kill the needed amount of Living Entities. (Affected by penalty)
			#Range: > 0
			Kill_Time = 30
			#List of entities that won't count towards removing the death timer. Add "//" to make it a whitelist instead. Add ';EntityClassification;' to block/allow mob categories. Usage: (ModId:EntityType) 'minecraft:zombie' or 'zombie' or 'minecraft'. Usage2: (EntityClassification) ';MONSTER;' or ';MISC;'
			Revive_Kill_Blacklist = []
			#If the Kill Revive particles should be hidden
			Hide_Kill_Revive_Effect = false

		["Self-Revive Settings"."Revive Type Settings"."Status Effects"]
			#List of harmful effects that shouldn't be chosen. Add "//" to make it a whitelist instead. You can also use parts of an effect Usage: (ModId:PotionEffect) 'minecraft:slowness' or 'slowness' or 'minecraft'
			Harmful_Effects_Blacklist = ["minecraft:bad_omen", "minecraft:unluck", "minecraft:instant_damage", "revive_me:kill_revive_effect"]
			#How long the harmful effects will last for. (Affected by penalty)
			#Range: > 0
			Effect_Duration = 15
			#If Revive effects should be disabled when reviving with this self-revive type.
			Disable_Revive_Effects = true
			#If negative effect particles should be hidden
			Hide_Negative_Effects = false

		["Self-Revive Settings"."Revive Type Settings".EXPERIENCE]
			#Percentage of XP you should lose to revive. (Affected by penalty)
			#Range: 0.0 ~ 1.0
			XP_Loss_Percentage = 0.4000000059604645
			#The minimum amount of XP levels needed.
			#Range: > 0
			Minimum_XP_Level = 15

["Fallen State Settings"]

	["Fallen State Settings"."General Settings"]
		#If fallen players can be targeted by mobs (will do the opposite if timer hits 0)
		Fallen_Is_Targetable = false
		#List of damage sources that bypass fallen state invulnerability (or the entire mod). Type "/" to allow all damage sources. Type "//" to make it a blacklist instead (entries will trigger the fallen state). You can also use parts of a damage source, add ';' to make it match exactly (Case sensitive both ways), add '*' to make it bypass the entire mod (does the opposite if set to blacklist). Usage: (MessageID) 'inWall' or 'Wall' or ';inWall', or '*inWall' or ';*inWall'
		Damage_Source_Whitelist = [";outOfWorld", ";genericKill"]
		#Max TOTAL revives (Setting to 0 will disable Revive Me!) (setting to -1 will disable the total-revive max) Refreshes when penalty timer ends.
		#Range: > -1
		Max_Total_revives = 6
		#Max PLAYER revives (setting to 0 will disable player-revive) (setting to -1 will disable the player-revive max) Refreshes when penalty timer ends.
		#Range: > -1
		Max_Player_revives = -1
		#Max SELF revives (setting to 0 will disable self-revive) (setting to -1 will disable the self-revive max) Refreshes when penalty timer ends.
		#Range: > -1
		Max_Self_revives = 3
		#Max distance another player can be to enter the fallen state (0 disables this)
		#Range: > 0
		Revive_Radius = 0
		#If Forge's Death Event should run first before this mod does (if Death event runs first and player death is cancelled, Revive-Me code will not execute. Same thing vice-versa.)
		Run_Death_Event_First = false
		#Potion effects the player has while fallen (ModId:PotionEffect:Amplification:HideEffect <-optional)(minecraft:slowness:0 or minecraft:blindness:0:true)
		Downed_Effects = ["minecraft:slowness:3:true"]
		#If you should die instantly if you disconnect while in the fallen state
		Die_On_Disconnect = false

		["Fallen State Settings"."General Settings"."Health & Heal Settings"]
			#Max Health you can have while in the fallen state, -1 is max health, Less than 1 is percentage
			#Range: -1.0 ~ 2.147483647E9
			Fallen_Health = 2.0
			#How much you have to be healed in order to be revived, 0 disables this feature, -1 is max health, Less than 1 is percentage
			#Range: -1.0 ~ 2.147483647E9
			Overheal_Amount = 0.0
			#Increases overheal cost each time you are revived, stacks additively.
			#Range: 0.0 ~ 2.147483647E9
			Overheal_Penalty_Percentage = 0.25

		["Fallen State Settings"."General Settings"."Attack & Damage Settings"]
			#Percentage of damage a fallen player recieves
			#Range: 0.0 ~ 2.147483647E9
			Fallen_Damage_Scale_In = 1.0
			#Percentage of damage a fallen player deals
			#Range: 0.0 ~ 2.147483647E9
			Fallen_Damage_Scale_Out = 1.0
			#How much damage you have to take to be revived, 0 disables this feature, -1 is max health, Less than 1 is percentage
			#Range: -1.0 ~ 2.147483647E9
			Overkill_Amount = 0.0
			#Increases overkill cost each time you are revived, stacks additively.
			#Range: 0.0 ~ 2.147483647E9
			Overkill_Penalty_Percentage = 0.25
			#What damage sources count towards overkill revive. Add "//" to make it a blacklist instead. Add ';Type;' to block/allow certain attackers. All types: ';NON_ENTITY;', ';NON_TEAM;', ';TEAM;', ';SELF;', ';MOB;', ';PLAYER;'. Type "/" to block/allow all damage sources
			Overkill_Whitelist = ["/", ";PLAYER;"]

		["Fallen State Settings"."General Settings"."Interaction Settings"]
			#If a fallen player can toggle the GUI on and off, will let them use items and attack if allowed
			Can_Toggle_GUI = true
			#If a fallen player can pick up items
			Can_Pick_Up_Items = true
			#If a fallen player can give up and die
			Can_Give_Up = true
			#If a fallen player can use their inventory
			#Allowed Values: NO, LOOK_ONLY, YES
			Interact_With_Inventory = "LOOK_ONLY"
			#Commands a fallen player isn't allowed to use. Type "/" to block all commands. Type "//" to make this a whitelist.
			Blocked_Commands = []
			#Keybinds that you can use while in the fallen state. (You can put a piece or the full name of a keybind. (Check the translation json for keybinding names (en_us.json for example))
			#Example of binding: 'key.fullscreen' or 'fullscreen' will let you use the 'Toggle Fullscreen' keybinding while in the fallen state. Add ';' to make the keybind only work when revive gui is toggled off)
			Allowed_Keybinds = []

			["Fallen State Settings"."General Settings"."Interaction Settings"."Call For Help Settings"]
				#How long the Help call will last in SECONDS
				#Range: 1.0 ~ 1.7976931348623157E308
				Revive_Help_Duration = 10.0
				#How far you can see glowing players
				#Range: 0.0 ~ 1.7976931348623157E308
				Revive_Glow_Max_Distance = 80.0
				#How far you can see the death timer for a player in the fallen state.
				#Range: 0.0 ~ 1.7976931348623157E308
				Death_Timer_Max_Distance = 40.0

	["Fallen State Settings"."Timer Settings"]
		#How long you have before death. Setting to -1 will disable the timer
		#Range: > -1
		Time_Left = 60
		#What happens when the timer ends, Targetable: Become targetable by mobs (does the opposite if Fallen_Is_Targetable is true), Death: Causes you to die, Revive: Uses self revive, if none left, uses player revive)
		#Allowed Values: TARGETABLE, DEATH, REVIVE
		Timer_Type = "TARGETABLE"
		#If the fallen timer should pause on disconnect (Multiplayer only)
		Pause_Fallen_Timer_On_Disconnect = false
		#How much time (in seconds) your death timer loses each time you fall. (Less than 1 is a percentage of max death time, -1 will take away the max)
		#Range: -1.0 ~ 1.7976931348623157E308
		Time_Reduction_Penalty = 5.0
		#how long the revive penalty effects will last in SECONDS
		#Range: 0.0 ~ 1.7976931348623157E308
		Revive_Penalty_Timer = 45.0
		#If you can remove the penalty timer before it ends
		Can_Remove_Penalty_Timer = false
		#If penalty timer particles should be hidden
		Hide_Penalty_Timer_Particles = true
		#How much time (in seconds) must pass before you may be killed by other players. Affected by time reduction penalty. Setting to -1 will disable this
		#Range: > -1
		PVP_Timer = 10

	["Fallen State Settings"."Movement & Camera Settings"]
		#What pose you have whilst fallen
		#Allowed Values: CROUCH, PRONE, SLEEP
		Fallen_Pose = "CROUCH"
		#What perspective you have whilst fallen
		#Allowed Values: DEFAULT, THIRD_PERSON, R_THIRD_PERSON, FIRST_PERSON
		Fallen_Perspective = "DEFAULT"
		#If the player may jump while fallen
		#Allowed Values: YES, LIQUID_ONLY, NO
		Can_Jump = "YES"
		#If the player may move while fallen
		Can_Move = true

["Revive Settings"]

	["Revive Settings"."Revivee Settings"]
		#If the reviver must look at the revivee to revive them
		Reviver_Must_look = true
		#How much health you will be revived with, -1 is max health, Less than 1 is percentage
		#Range: -1.0 ~ 2.147483647E9
		Revive_Health = 10.0
		#How much food you will be revived with, -1 is max food, Less than 1 is percentage
		#Range: -1.0 ~ 2.147483647E9
		Revive_Food = 6.0
		#What effects you revive with (ModId:PotionEffect:Amplification:Ticks:HideEffect <-optional)(minecraft:fire_resistance:3:100 or minecraft:resistance:3:100:true)
		Revive_Effects = ["minecraft:fire_resistance:5:100:true", "minecraft:resistance:5:100:true"]
		#Give back all of the potion effects the player had before entering the fallen state
		Revert_Effects_On_Revive = false
		#What effects you won't gain back on revive. Add "//" to make it a whitelist instead. Add ';MobEffectCategory;' to block/allow effect categories. Usage: (ModId:PotionEffect) 'minecraft:slowness' or 'slowness' or 'minecraft'. Usage2: (MobEffectCategory) ';HARMFUL;' or ';NEUTRAL;' or ';BENEFICIAL;'
		Revert_Effect_Blacklist = ["revive_me"]

	["Revive Settings"."Reviver Settings"]
		#How long to revive someone
		#Range: > 0
		Revive_Time = 3
		#What the reviver will lose (Reviver can use ITEM without it being selected. Selecting ITEM while Revive Items are disabled will disable this revive option.)
		#Allowed Values: NONE, HEALTH, EXPERIENCE, FOOD, ITEM
		Penalty_Type = "FOOD"
		#Amount that will be taken from reviver, Numbers below 1 and greater than 0 will turn it into a percentage
		Penalty_Amount = 10.0
		#If revive progress resets when damage is taken
		Reset_Revive_On_Hit = true

["Chat Settings"]
	#Silence the revive and fallen chat messages
	Silence_Regular_Messages = false
	#Silence command chat messages
	Silence_Command_Messages = false
	#If chat messages from this mod should be sent to everyone. If false, will only send to those nearby
	Universal_Chat_Messages = true

["Client Settings"]
	#Makes self-revive UI smaller, more compact
	Compact_UI = false
	#If the UI text should use bold formatting
	Bold_Text = true
	#If item info should be shown on Revive Item Screen
	Show_Item_Page = true
	#If Revive items should have extended tooltips
	Show_Tool_Tip = true
	#Controls how loud Revive Me! sounds are
	#Range: 0.0 ~ 1.0
	Sound_Level = 0.699999988079071

