#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Sep 29 17:45:13 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
enableShaders=true
